import { Component } from '@angular/core';
import {NavController, NavParams} from 'ionic-angular';


@Component({
 selector:"rout-sov",
 templateUrl: 'sov.html',
})
export class RoutSov {

 items = [];
 backs= [];
 item:any;

	menubtn: string = "out";
	isAndroid: boolean = true;

 constructor(public navCtrl: NavController, params: NavParams) {

this.menubtn= "out";
this.item = params.data.item;
 
  this.items = [
				{'title':'Калининград Южный',
				'bullet_type':'def start',
				'time':'18:10',
				},
				{'title':'Калининград Северный',
				'bullet_type':'def',
				'time':'18:19',
				},
				{'title':'Кутузово-Новое',
				'bullet_type':'def',
				'time':'18:25',
				},
				{'title':'Гурьевск-центральный ',
				'bullet_type':'def',
				'time':'18:32',
				},
				{'title':'Гурьевск-новый',
				'bullet_type':'def',
				'time':'18:37',
				},
				{'title':'Баевка-1 ',
				'bullet_type':'def',
				'time':'18:45',
				},
				{'title':'Баевка-2 ',
				'bullet_type':'def',
				'time':'18:49',
				},
				{'title':'Добрино ',
				'bullet_type':'def',
				'time':'18:54',
				},
				{'title':'Славянское',
				'bullet_type':'def',
				'time':'19:02',
				},
				{'title':'Полесск',
				'bullet_type':'def',
				'time':'19:11',
				},
				{'title':'Шолохово',
				'bullet_type':'def',
				'time':'19:20',
				},
				{'title':'Петино',
				'bullet_type':'def',
				'time':'19:25',
				},
				{'title':'Богатово',
				'bullet_type':'def',
				'time':'19:31',
				},
				{'title':'Залесье',
				'bullet_type':'def',
				'time':'19:40',
				},
				{'title':'Большаково',
				'bullet_type':'def',
				'time':'19:48',
				},
				{'title':'Славск',
				'bullet_type':'def',
				'time':'20:02',
				},
				{'title':'Щегловка',
				'bullet_type':'def',
				'time':'20:06',
				},
				{'title':'Ржевское',
				'bullet_type':'def',
				'time':'20:12',
				},
				{'title':'119 км',
				'bullet_type':'def',
				'time':'20:17',
				},
				{'title':'Советск',
				'bullet_type':'def start',
				'time':'20:26',
				},

  ],

  this.backs = [
				{'title':'Советск',
				'bullet_type':'def start',
				'time':'06:29',
				'time2':'17:52',
				},
				{'title':'119 км',
				'bullet_type':'def',
				'time':'06:39',
				'time2':'18:02',
				},
				{'title':'Ржевское',
				'bullet_type':'def',
				'time':'06:44',
				'time2':'18:07',
				},
				{'title':'Щегловка',
				'bullet_type':'def',
				'time':'06:50',
				'time2':'18:13',
				},
				{'title':'Славск',
				'bullet_type':'def',
				'time':'06:55',
				'time2':'18:18',
				},
				{'title':'Большаково',
				'bullet_type':'def',
				'time':'07:09',
				'time2':'18:32',
				},
				{'title':'Залесье',
				'bullet_type':'def',
				'time':'07:17',
				'time2':'18:42',
				},
				{'title':'Богатово',
				'bullet_type':'def',
				'time':'07:26',
				'time2':'18:51',
				},
				{'title':'Петино',
				'bullet_type':'def',
				'time':'07:31',
				'time2':'18:56',
				},
				{'title':'Шолохово',
				'bullet_type':'def',
				'time':'07:36',
				'time2':'19:01',
				},
				{'title':'Полесск',
				'bullet_type':'def',
				'time':'07:45',
				'time2':'19:11',
				},
				{'title':'Славянское',
				'bullet_type':'def',
				'time':'07:53',
				'time2':'19:20',
				},
				{'title':'Добрино',
				'bullet_type':'def',
				'time':'08:01',
				'time2':'19:28',
				},
				{'title':'Баевка-2',
				'bullet_type':'def',
				'time':'08:06',
				'time2':'19:33',
				},
				{'title':'Баевка-1',
				'bullet_type':'def',
				'time':'08:10',
				'time2':'19:37',
				},
				{'title':'Гурьевск-новый',
				'bullet_type':'def',
				'time':'08:18',
				'time2':'19:45',
				},
				{'title':'Гурьевск-центральный',
				'bullet_type':'var',
				'time':'08:24',
				'time2':'--:--',
				},
				{'title':'Кутузово-Новое',
				'bullet_type':'def',
				'time':'08:31',
				'time2':'19:56',
				},
				{'title':'Калининград Северный',
				'bullet_type':'def',
				'time':'08:39',
				'time2':'20:04',
				},
				{'title':'Калининград Южный',
				'bullet_type':'def start',
				'time':'08:46',
				'time2':'20:11',
				},
  			]
   }

// Навигация. 

 goToRout(item) {
 this.navCtrl.push(RoutSov , { item: item });
 }

}