import { Component } from '@angular/core';
import {NavController, NavParams} from 'ionic-angular';


@Component({
 selector:"rout-svt",
 templateUrl: 'svt.html',
})
export class RoutSvt {

 items = [];
 backs= [];
 item:any;

	menubtn: string = "out";
	isAndroid: boolean = true;

 constructor(public navCtrl: NavController, params: NavParams) {

this.menubtn= "out";
this.item = params.data.item;
 
  this.items = [
				{'title':'Калининград Южный',
				'bullet_type':'def start',
				'time':'08:00', //6900
				'time2':'06:23',
				},
				{'title':'Калининград Северный',
				'bullet_type':'def',
				'time':'08:08',
				'time2':'06:23',
				},
				{'title':'Кутузово-Новое',
				'bullet_type':'def',
				'time':'08:14',
				'time2':'06:23',
				},
				{'title':'7 км',
				'bullet_type':'def',
				'time':'08:21',
				'time2':'06:23',
				},
				{'title':'Рябиновка',
				'bullet_type':'def',
				'time':'08:25',
				'time2':'06:23',
				},
				{'title':'Каштановка',
				'bullet_type':'def',
				'time':'08:30',
				'time2':'06:23',
				},
				{'title':'Муромское',
				'bullet_type':'def',
				'time':'08:34',
				'time2':'06:23',
				},
				{'title':'Сосновка',
				'bullet_type':'disable',
				'time':'--:--',
				'time2':'06:23',
				},
				{'title':'Зеленоградск-новый',
				'bullet_type':'def',
				'time':'08:57',
				'time2':'06:23',
				},
				{'title':'Малиновка',
				'bullet_type':'def',
				'time':'09:01',
				'time2':'06:23',
				},
				{'title':'Сокольники-1',
				'bullet_type':'def',
				'time':'09:04',
				'time2':'06:23',
				},
				{'title':'Сокольники-2',
				'bullet_type':'def',
				'time':'09:07',
				'time2':'06:23',
				},
				{'title':'Рощино',
				'bullet_type':'def',
				'time':'09:11',
				'time2':'06:23',
				},
				{'title':'Куликово',
				'bullet_type':'def',
				'time':'09:14',
				'time2':'06:23',
				},
				{'title':'Пионерский Курорт',
				'bullet_type':'def',
				'time':'09:22',
				'time2':'06:23',
				},
				{'title':'Светлогорск-1',
				'bullet_type':'def',
				'time':'09:29',
				'time2':'06:23',
				},
				{'title':'Светлогорск-2',
				'bullet_type':'def start',
				'time':'09:34',
				'time2':'06:23',
				},
				
  ],

  this.backs = [
				{'title':'Светлогорск-2',
				'bullet_type':'def start',
				'time':'10:04', //6902
				'time2':'--:--',
				},
				{'title':'Светлогорск-1',
				'bullet_type':'var',
				'time':'10:10',
				'time2':'--:--',
				},
				{'title':'Пионерский Курорт',
				'bullet_type':'def',
				'time':'10::16',
				'time2':'06:05',
				},
				{'title':'Куликово',
				'bullet_type':'def',
				'time':'10::24',
				'time2':'06:13',
				},
				{'title':'Рощино',
				'bullet_type':'def',
				'time':'10::27',
				'time2':'06:16',
				},
				{'title':'Сокольники-2',
				'bullet_type':'def',
				'time':'10::31',
				'time2':'06:20',
				},
				{'title':'Сокольники-1',
				'bullet_type':'def',
				'time':'10::34',
				'time2':'06:23',
				},
				{'title':'Малиновка',
				'bullet_type':'def',
				'time':'10::37',
				'time2':'06:26',
				},
				{'title':'Зеленоградск-новый',
				'bullet_type':'def',
				'time':'10:55',
				'time2':'06:45',
				},
				{'title':'Сосновка',
				'bullet_type':'def',
				'time':'11:01',
				'time2':'06:51',
				},
				{'title':'Муромское',
				'bullet_type':'def',
				'time':'11:05',
				'time2':'06:55',
				},
				{'title':'Каштановка',
				'bullet_type':'def',
				'time':'11:09',
				'time2':'06:59',
				},
				{'title':'Рябиновка',
				'bullet_type':'def',
				'time':'11:15',
				'time2':'07:04',
				},
				{'title':'7 км',
				'bullet_type':'def',
				'time':'11:19',
				'time2':'07:08',
				},
				{'title':'Кутузово-Новое',
				'bullet_type':'def',
				'time':'11:26',
				'time2':'07:15',
				},
				{'title':'Калининград Северный',
				'bullet_type':'def',
				'time':'11:33',
				'time2':'07:22',
				},
				{'title':'Калининград Южный',
				'bullet_type':'def start',
				'time':'11:39',
				'time2':'07:28',
				},
  			]
   }

// Навигация. 

 goToRout(item) {
 this.navCtrl.push(RoutSvt , { item: item });
 }

}